org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.daemon=true
org.gradle.workers.max=4
kotlin.daemon.jvmargs=-Xmx384m
kotlin.compiler.execution.strategy=in-process
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=true
